on:
  push:
  pull_request:

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [
          { arch: "aarch64", manylinux: "manylinux2014" },
          { arch: "aarch64", manylinux: "manylinux_2_24" },
          { arch: "aarch64", manylinux: "manylinux_2_27" },
          { arch: "armv7l", manylinux: "manylinux2014" },
          { arch: "armv7l", manylinux: "manylinux_2_24" },
          { arch: "armv7l", manylinux: "manylinux_2_27" },
          { arch: "s390x", manylinux: "manylinux2014" },
          { arch: "s390x", manylinux: "manylinux_2_24" },
          { arch: "s390x", manylinux: "manylinux_2_27" },
          { arch: "ppc64le", manylinux: "manylinux2014" },
          { arch: "ppc64le", manylinux: "manylinux_2_24" },
          { arch: "ppc64le", manylinux: "manylinux_2_27" },
          { arch: "ppc64", manylinux: "manylinux2014" },  # ppc64 only supported in manylinux2014
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.platform.arch }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform.arch }}-buildx-
      - name: Clean Docker cache
        if: "contains(github.event.head_commit.message, '[clean cache]')"
        continue-on-error: true
        run: |
          rm -rf /tmp/.buildx-cache
      - name: Build amd64 image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: ${{ matrix.platform.manylinux }}/${{ matrix.platform.arch }}
          file: ${{ matrix.platform.manylinux }}/${{ matrix.platform.arch }}/Dockerfile
          tags: messense/${{ matrix.platform.manylinux }}-cross:${{ matrix.platform.arch }}-amd64
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          # Temp fix
          # https://github.com/docker/build-push-action/issues/252
          # https://github.com/moby/buildkit/issues/1896
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Build and push multiarch image
        if: github.ref == 'refs/heads/master'
        env:
          ARCH: ${{ matrix.platform.arch }}
          NAME: ${{ matrix.platform.manylinux }}
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push messense/$NAME-cross:$ARCH-amd64

          echo "image: messense/$NAME-cross:$ARCH
          manifests:
            - image: messense/$NAME-cross:$ARCH-amd64
              platform:
                architecture: amd64
                os: linux
            - image: messense/$NAME-cross:$ARCH-arm64
              platform:
                architecture: arm64
                os: linux
          " > manifest.yaml

          curl -sqL -o manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64
          chmod +x manifest-tool
          ./manifest-tool push from-spec manifest.yaml
      - name: Alias armv7l to armv7
        if: matrix.platform.arch == 'armv7l' && github.ref == 'refs/heads/master'
        env:
          NAME: ${{ matrix.platform.manylinux }}
        run: |
          echo "image: messense/$NAME-cross:armv7
          manifests:
            - image: messense/$NAME-cross:armv7l-amd64
              platform:
                architecture: amd64
                os: linux
            - image: messense/$NAME-cross:armv7l-arm64
              platform:
                architecture: arm64
                os: linux
          " > manifest.yaml

          curl -sqL -o manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64
          chmod +x manifest-tool
          ./manifest-tool push from-spec manifest.yaml
